version: "3.6"
services:
    simplemysql-tester:
        build:
            context: ../
            dockerfile: ./dev/Dockerfile-mocha
        image: simplemysql-tester
        container_name: simplemysql-tester
        networks:
            - default

    
networks:
    default:
        name: mysql-test-net